// Copyright (c) Oddbit (https://oddbit.id)
//
// This source file is part of facebook_app_events.
// Licensed under the Apache License, Version 2.0. See LICENSE and NOTICE.

import 'dart:async';
import 'dart:convert';

import 'package:flutter/services.dart';

import 'src/enums.dart';

export 'src/enums.dart';

part 'src/standard_events.dart';

/// MethodChannel name used by the plugin.
const channelName = 'flutter.oddbit.id/facebook_app_events';

/// A thin Flutter wrapper around Meta's native **Facebook App Events** SDKs.
///
/// Most methods in this class map directly to native SDK calls.
/// For expected behavior and platform-specific details, see documentation
/// [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
/// and
/// [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html).
///
/// For the full API reference generated by pub.dev, see:
/// https://pub.dev/documentation/facebook_app_events/latest/
class FacebookAppEvents {
  static const _channel = MethodChannel(channelName);

  /// Common event names.
  ///
  /// These are the standard event names used by Meta App Events. See documentation:
  /// https://developers.facebook.com/docs/app-events/best-practices#standard-events
  ///
  /// Android SDK reference for constants:
  /// https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventsconstants.html
  static const eventNameCompletedRegistration =
      'fb_mobile_complete_registration';
  static const eventNameViewedContent = 'fb_mobile_content_view';
  static const eventNameRated = 'fb_mobile_rate';
  static const eventNameInitiatedCheckout = 'fb_mobile_initiated_checkout';
  static const eventNameAddedToCart = 'fb_mobile_add_to_cart';
  static const eventNameAddedToWishlist = 'fb_mobile_add_to_wishlist';
  static const eventNameSubscribe = "Subscribe";
  static const eventNameStartTrial = "StartTrial";
  static const eventNameAdImpression = "AdImpression";
  static const eventNameAdClick = "AdClick";
  static const eventNameAchievedLevel = "fb_mobile_level_achieved";
  static const eventNameAddedPaymentInfo = "fb_mobile_add_payment_info";
  static const eventNameCompletedTutorial = "fb_mobile_tutorial_completion";
  static const eventNameSearched = "fb_mobile_search";
  static const eventNameSpentCredits = "fb_mobile_spent_credits";
  static const eventNameUnlockedAchievement = "fb_mobile_achievement_unlocked";
  static const eventNameContact = "Contact";
  static const eventNameCustomizeProduct = "CustomizeProduct";
  static const eventNameDonate = "Donate";
  static const eventNameFindLocation = "FindLocation";
  static const eventNameSchedule = "Schedule";
  static const eventNameSubmitApplication = "SubmitApplication";

  static const _paramNameValueToSum = "_valueToSum";
  static const paramNameAdType = "fb_ad_type";
  static const paramNameCurrency = "fb_currency";
  static const paramNameOrderId = "fb_order_id";
  static const paramNameRegistrationMethod = "fb_registration_method";
  static const paramNamePaymentInfoAvailable = "fb_payment_info_available";
  static const paramNameNumItems = "fb_num_items";
  static const paramNameLevel = "fb_level";
  static const paramNameSearchString = "fb_search_string";
  static const paramNameDescription = "fb_description";
  static const paramValueYes = "1";
  static const paramValueNo = "0";

  /// Parameter key used to specify a generic content type/family for the logged event, e.g.
  /// "music", "photo", "video".  Options to use will vary depending on the nature of the app.
  static const paramNameContentType = "fb_content_type";

  /// Parameter key used to specify data for the one or more pieces of content being logged about.
  /// Data should be a JSON encoded string.
  /// Example:
  ///   "[{\"id\": \"1234\", \"quantity\": 2, \"item_price\": 5.99}, {\"id\": \"5678\", \"quantity\": 1, \"item_price\": 9.99}]"
  static const paramNameContent = "fb_content";

  /// Parameter key used to specify an ID for the specific piece of content being logged about.
  /// This could be an EAN, article identifier, etc., depending on the nature of the app.
  static const paramNameContentId = "fb_content_id";

  /// Notifies the Facebook SDK that the app has launched ("activate app").
  ///
  /// In the default configuration, App Install/App Launch events are logged
  /// automatically by the native Facebook SDK.
  ///
  /// Call this method only if you have disabled or delayed automatic app event
  /// logging (for example to obtain user consent) and want to log activation
  /// manually after enabling/initializing the SDK.
  ///
  /// If `FacebookAutoLogAppEventsEnabled` (iOS) or
  /// `com.facebook.sdk.AutoLogAppEventsEnabled` (Android) is set to `false`,
  /// call this method to log activation and install events manually.
  ///
  /// If you provide an [applicationId], the native SDK will be configured to
  /// log to that App ID instead of the default app id from platform config.
  /// (On iOS this uses `loggingOverrideAppID`; on Android it is passed to
  /// `activateApp(Application, applicationId)`.) The override applies per
  /// call: calling [activateApp] again without an [applicationId] reverts to
  /// the default app id on both platforms.
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<void> activateApp({String? applicationId}) {
    final args = <String, dynamic>{
      'applicationId': applicationId,
    };

    return _channel.invokeMethod<void>('activateApp', _filterOutNulls(args));
  }

  /// Clears any user data previously set via [setUserData].
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<void> clearUserData() {
    return _channel.invokeMethod<void>('clearUserData');
  }

  /// Sets user data to associate with all app events.
  /// All user data are hashed and used to match Facebook user from this
  /// instance of an application. The user data will be persisted between
  /// application instances.
  ///
  /// Merge semantics: only the fields you pass are updated; fields that are
  /// `null` (or omitted) keep their previously-set value on both platforms.
  /// To remove fields use [clearUserData] (all fields) or
  /// [clearUserDataForType] (single field, iOS only).
  ///
  /// [externalId] is your own identifier for the user, used by Meta for
  /// advanced matching (`extern_id`).
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<void> setUserData({
    String? email,
    String? firstName,
    String? lastName,
    String? phone,
    String? dateOfBirth,
    String? gender,
    String? city,
    String? state,
    String? zip,
    String? country,
    String? externalId,
  }) {
    final args = <String, dynamic>{
      'email': email,
      'firstName': firstName,
      'lastName': lastName,
      'phone': phone,
      'dateOfBirth': dateOfBirth,
      'gender': gender,
      'city': city,
      'state': state,
      'zip': zip,
      'country': country,
      'externalId': externalId,
    };

    return _channel.invokeMethod<void>('setUserData', _filterOutNulls(args));
  }

  /// Clears the currently set user id.
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<void> clearUserID() {
    return _channel.invokeMethod<void>('clearUserID');
  }

  /// Explicitly flush any stored events to the server.
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<void> flush() {
    return _channel.invokeMethod<void>('flush');
  }

  /// Returns the app ID this logger was configured to log to.
  ///
  /// Maps to `appEventsLogger.applicationId` on Android and
  /// `Settings.shared.appID` on iOS — both resolve the app id from platform
  /// configuration (`AndroidManifest.xml` / `Info.plist`) and reflect any app
  /// id set programmatically on the SDK.
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/ios/getting-started)
  /// - [Android](https://developers.facebook.com/docs/android/getting-started)
  Future<String?> getApplicationId() {
    return _channel.invokeMethod<String>('getApplicationId');
  }

  /// Returns the anonymous app device GUID / anonymous ID used by the SDK.
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<String?> getAnonymousId() {
    return _channel.invokeMethod<String>('getAnonymousId');
  }

  /// Log an app event with the specified [name] and the supplied [parameters] value.
  ///
  /// The native SDKs only accept `String` and numeric parameter values; an
  /// event containing any other value type is silently dropped by the SDK.
  /// This method therefore accepts `String`, `num`, and `bool` values —
  /// booleans are converted to `"1"`/`"0"` (Meta's yes/no convention, see
  /// [paramValueYes]/[paramValueNo]) so the event is recorded identically on
  /// both platforms. Any other value type (lists, maps, ...) throws an
  /// [ArgumentError]; encode structured values as a JSON string first (as
  /// Meta prescribes for [paramNameContent]).
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<void> logEvent({
    required String name,
    Map<String, dynamic>? parameters,
    double? valueToSum,
  }) {
    final args = <String, dynamic>{
      'name': name,
      _paramNameValueToSum: valueToSum,
    };

    if (parameters != null) {
      args['parameters'] = _normalizeParameters(parameters);
    }

    return _channel.invokeMethod<void>('logEvent', _filterOutNulls(args));
  }

  /// Logs an app event that tracks that the application was open via Push Notification.
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<void> logPushNotificationOpen({
    required Map<String, dynamic> payload,
    String? action,
  }) {
    final args = <String, dynamic>{
      'payload': payload,
      'action': action,
    };

    return _channel.invokeMethod<void>('logPushNotificationOpen', args);
  }

  /// Sets a user [id] to associate with all app events.
  /// This can be used to associate your own user id with the
  /// app events logged from this instance of an application.
  /// The user ID will be persisted between application instances.
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<void> setUserID(String id) {
    return _channel.invokeMethod<void>('setUserID', id);
  }

  /// Log this event when the user has completed registration with the app.
  /// Parameter [registrationMethod] is used to specify the method the user has
  /// used to register for the app, e.g. "Facebook", "email", "Google", etc.
  ///
  /// See documentation:
  /// - [Standard events](https://developers.facebook.com/docs/app-events/best-practices#standard-events)
  /// - [Android constants](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventsconstants.html)
  Future<void> logCompletedRegistration({
    String? registrationMethod,
    Map<String, dynamic>? parameters,
  }) {
    return logEvent(
      name: eventNameCompletedRegistration,
      parameters: {
        if (parameters != null) ...parameters,
        if (registrationMethod != null)
          paramNameRegistrationMethod: registrationMethod,
      },
    );
  }

  /// Log this event when the user has rated an item in the app.
  ///
  /// See documentation:
  /// - [Standard events](https://developers.facebook.com/docs/app-events/best-practices#standard-events)
  /// - [Android constants](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventsconstants.html)
  Future<void> logRated({
    double? valueToSum,
    Map<String, dynamic>? parameters,
  }) {
    return logEvent(
      name: eventNameRated,
      valueToSum: valueToSum,
      parameters: parameters,
    );
  }

  /// Log this event when the user has viewed a form of content in the app.
  ///
  /// To be eligible for ad revenue optimization (ROAS), you should include the
  /// [price] (as valueToSum) and [currency] parameters.
  ///
  /// See documentation:
  /// - [Standard events](https://developers.facebook.com/docs/app-events/best-practices#standard-events)
  /// - [Android constants](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventsconstants.html)
  Future<void> logViewContent({
    Map<String, dynamic>? content,
    String? id,
    String? type,
    String? currency,
    double? price,
    Map<String, dynamic>? parameters,
  }) {
    return logEvent(
      name: eventNameViewedContent,
      parameters: {
        if (parameters != null) ...parameters,
        if (content != null) paramNameContent: json.encode(content),
        if (id != null) paramNameContentId: id,
        if (type != null) paramNameContentType: type,
        if (currency != null) paramNameCurrency: currency,
      },
      valueToSum: price,
    );
  }

  /// Log this event when the user has added an item to cart.
  ///
  /// To be eligible for ad revenue optimization (ROAS), you should include the
  /// [price] (as valueToSum) and [currency] parameters.
  ///
  /// See documentation:
  /// - [Standard events](https://developers.facebook.com/docs/app-events/best-practices#standard-events)
  /// - [Android constants](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventsconstants.html)
  Future<void> logAddToCart({
    Map<String, dynamic>? content,
    required String id,
    required String type,
    required String currency,
    required double price,
    Map<String, dynamic>? parameters,
  }) {
    return logEvent(
      name: eventNameAddedToCart,
      parameters: {
        if (parameters != null) ...parameters,
        if (content != null) paramNameContent: json.encode(content),
        paramNameContentId: id,
        paramNameContentType: type,
        paramNameCurrency: currency,
      },
      valueToSum: price,
    );
  }

  /// Log this event when the user has added an item to wishlist.
  ///
  /// To be eligible for ad revenue optimization (ROAS), you should include the
  /// [price] (as valueToSum) and [currency] parameters.
  ///
  /// See documentation:
  /// - [Standard events](https://developers.facebook.com/docs/app-events/best-practices#standard-events)
  /// - [Android constants](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventsconstants.html)
  Future<void> logAddToWishlist({
    Map<String, dynamic>? content,
    required String id,
    required String type,
    required String currency,
    required double price,
    Map<String, dynamic>? parameters,
  }) {
    return logEvent(
      name: eventNameAddedToWishlist,
      parameters: {
        if (parameters != null) ...parameters,
        if (content != null) paramNameContent: json.encode(content),
        paramNameContentId: id,
        paramNameContentType: type,
        paramNameCurrency: currency,
      },
      valueToSum: price,
    );
  }

  /// Enables/disables automatic app event logging.
  ///
  /// This is commonly used for consent flows (e.g. GDPR) where you want to
  /// delay automatic logging until the user has consented.
  ///
  /// See documentation:
  /// - https://developers.facebook.com/docs/app-events/gdpr-compliance
  /// - [iOS Settings](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/settings.html)
  /// - [Android FacebookSdk](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/FacebookSdk.html)
  Future<void> setAutoLogAppEventsEnabled(bool enabled) {
    return _channel.invokeMethod<void>('setAutoLogAppEventsEnabled', enabled);
  }

  /// Sets data processing options (CCPA / Limited Data Use).
  ///
  /// Maps to `FacebookSdk.setDataProcessingOptions(options, country, state)`
  /// on Android and `Settings.shared.setDataProcessingOptions(options,
  /// country:state:)` on iOS.
  ///
  /// For example, to enable Limited Data Use with geolocation:
  /// `setDataProcessingOptions(['LDU'], country: 0, state: 0)`. Passing an
  /// empty [options] list disables Limited Data Use.
  ///
  /// See documentation:
  /// - https://developers.facebook.com/docs/development/data-processing-options
  /// - [iOS Settings](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/settings.html)
  /// - [Android FacebookSdk](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/FacebookSdk.html)
  Future<void> setDataProcessingOptions(
    List<String> options, {
    int? country,
    int? state,
  }) {
    final args = <String, dynamic>{
      'options': options,
      'country': country,
      'state': state,
    };

    return _channel.invokeMethod<void>('setDataProcessingOptions', args);
  }

  /// Logs a purchase event.
  ///
  /// [currency] should be an ISO 4217 currency code (for example: `"USD"`).
  ///
  /// [parameters] follows the same value-type rules as [logEvent]: `String`,
  /// `num`, and `bool` (sent as `"1"`/`"0"`); other types throw an
  /// [ArgumentError].
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<void> logPurchase({
    required double amount,
    required String currency,
    Map<String, dynamic>? parameters,
  }) {
    final args = <String, dynamic>{
      'amount': amount,
      'currency': currency,
      if (parameters != null) 'parameters': _normalizeParameters(parameters),
    };
    return _channel.invokeMethod<void>('logPurchase', _filterOutNulls(args));
  }

  /// Convenience wrapper around [logEvent] for the Initiated Checkout
  /// standard event.
  ///
  /// To be eligible for ad revenue optimization (ROAS), you should include the
  /// [totalPrice] (as valueToSum) and [currency] parameters.
  ///
  /// See documentation:
  /// - https://developers.facebook.com/docs/app-events/best-practices#standard-events
  Future<void> logInitiatedCheckout({
    double? totalPrice,
    String? currency,
    String? contentType,
    String? contentId,
    int? numItems,
    bool paymentInfoAvailable = false,
    Map<String, dynamic>? parameters,
  }) {
    return logEvent(
      name: eventNameInitiatedCheckout,
      valueToSum: totalPrice,
      parameters: {
        if (parameters != null) ...parameters,
        if (contentType != null) paramNameContentType: contentType,
        if (contentId != null) paramNameContentId: contentId,
        if (numItems != null) paramNameNumItems: numItems,
        if (currency != null) paramNameCurrency: currency,
        paramNamePaymentInfoAvailable:
            paymentInfoAvailable ? paramValueYes : paramValueNo,
      },
    );
  }

  /// Sets advertiser tracking / advertiser ID collection flags.
  ///
  /// Deprecated because the two flags it couples no longer exist as a pair on
  /// either platform:
  ///
  /// - On iOS, `Settings.isAdvertiserTrackingEnabled` is deprecated since
  ///   Facebook SDK v17: the SDK derives tracking consent from
  ///   `ATTrackingManager.trackingAuthorizationStatus` and ignores this setter
  ///   on iOS 17+. Request App Tracking Transparency authorization in your
  ///   app instead.
  /// - On Android, no tracking-enabled flag exists; only advertiser ID
  ///   collection is configurable, and this method reduces to
  ///   `setAdvertiserIDCollectionEnabled(enabled && collectId)`.
  ///
  /// Use [setAdvertiserIdCollectionEnabled] instead, which maps 1:1 to the
  /// native setting on both platforms.
  @Deprecated('Use setAdvertiserIdCollectionEnabled instead. On iOS the SDK '
      'derives tracking consent from App Tracking Transparency, and on '
      'Android only advertiser ID collection is configurable.')
  Future<void> setAdvertiserTracking({
    required bool enabled,
    bool collectId = true,
  }) {
    final args = <String, dynamic>{
      'enabled': enabled,
      'collectId': collectId,
    };

    return _channel.invokeMethod<void>('setAdvertiserTracking', args);
  }

  /// Enables/disables collection of the device advertiser ID (IDFA on iOS,
  /// Google Advertising ID on Android) with logged events.
  ///
  /// Maps to `Settings.shared.isAdvertiserIDCollectionEnabled` (iOS) and
  /// `FacebookSdk.setAdvertiserIDCollectionEnabled` (Android). Align this
  /// with your user consent flow.
  ///
  /// Note that on iOS the advertiser ID is only available when the user has
  /// granted App Tracking Transparency authorization.
  ///
  /// See documentation:
  /// - [iOS Settings](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/settings.html)
  /// - [Android FacebookSdk](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/FacebookSdk.html)
  Future<void> setAdvertiserIdCollectionEnabled(bool enabled) {
    return _channel.invokeMethod<void>(
      'setAdvertiserIdCollectionEnabled',
      enabled,
    );
  }

  /// Restricts logged event data from being used for purposes other than
  /// analytics and conversions (e.g. targeting ads to the user).
  ///
  /// Maps to `FacebookSdk.setLimitEventAndDataUsage` (Android) and
  /// `Settings.shared.isEventDataUsageLimited` (iOS). The setting is
  /// persisted across app launches. Defaults to `false`.
  ///
  /// See documentation:
  /// - [iOS Settings](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/settings.html)
  /// - [Android FacebookSdk](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/FacebookSdk.html)
  Future<void> setLimitEventAndDataUsage(bool enabled) {
    return _channel.invokeMethod<void>('setLimitEventAndDataUsage', enabled);
  }

  /// The start of a paid subscription for a product or service you offer.
  ///
  /// To be eligible for ad revenue optimization (ROAS), you should include the
  /// [price] (as valueToSum) and [currency] parameters.
  ///
  /// See documentation:
  /// - https://developers.facebook.com/docs/app-events/best-practices#standard-events
  Future<void> logSubscribe({
    double? price,
    String? currency,
    required String orderId,
    Map<String, dynamic>? parameters,
  }) {
    return logEvent(
      name: eventNameSubscribe,
      valueToSum: price,
      parameters: {
        if (parameters != null) ...parameters,
        if (currency != null) paramNameCurrency: currency,
        paramNameOrderId: orderId,
      },
    );
  }

  /// The start of a free trial of a product or service you offer (example: trial subscription).
  ///
  /// To be eligible for ad revenue optimization (ROAS), you should include the
  /// [price] (as valueToSum) and [currency] parameters.
  ///
  /// See documentation:
  /// - https://developers.facebook.com/docs/app-events/best-practices#standard-events
  Future<void> logStartTrial({
    double? price,
    String? currency,
    required String orderId,
    Map<String, dynamic>? parameters,
  }) {
    return logEvent(
      name: eventNameStartTrial,
      valueToSum: price,
      parameters: {
        if (parameters != null) ...parameters,
        if (currency != null) paramNameCurrency: currency,
        paramNameOrderId: orderId,
      },
    );
  }

  /// Log this event when the user views an ad.
  ///
  /// To track ad revenue for ROAS optimization, use [logEvent] directly with
  /// [eventNameAdImpression], passing `valueToSum` (the ad revenue amount) and
  /// [paramNameCurrency] in the parameters map:
  ///
  /// ```dart
  /// logEvent(
  ///   name: FacebookAppEvents.eventNameAdImpression,
  ///   valueToSum: revenueAmount,
  ///   parameters: {
  ///     FacebookAppEvents.paramNameAdType: 'interstitial',
  ///     FacebookAppEvents.paramNameCurrency: 'USD',
  ///   },
  /// );
  /// ```
  ///
  /// See documentation:
  /// - https://developers.facebook.com/docs/app-events/guides/maximize-in-app-ad-revenue
  /// - https://developers.facebook.com/docs/app-events/best-practices#standard-events
  Future<void> logAdImpression({
    required String adType,
  }) {
    return logEvent(
      name: eventNameAdImpression,
      parameters: {
        paramNameAdType: adType,
      },
    );
  }

  /// Log this event when the user clicks an ad.
  ///
  /// To track ad revenue for ROAS optimization, use [logEvent] directly with
  /// [eventNameAdClick], passing `valueToSum` (the ad revenue amount) and
  /// [paramNameCurrency] in the parameters map:
  ///
  /// ```dart
  /// logEvent(
  ///   name: FacebookAppEvents.eventNameAdClick,
  ///   valueToSum: revenueAmount,
  ///   parameters: {
  ///     FacebookAppEvents.paramNameAdType: 'rewarded_video',
  ///     FacebookAppEvents.paramNameCurrency: 'USD',
  ///   },
  /// );
  /// ```
  ///
  /// See documentation:
  /// - https://developers.facebook.com/docs/app-events/guides/maximize-in-app-ad-revenue
  /// - https://developers.facebook.com/docs/app-events/best-practices#standard-events
  Future<void> logAdClick({
    required String adType,
  }) {
    return logEvent(
      name: eventNameAdClick,
      parameters: {
        paramNameAdType: adType,
      },
    );
  }

  /// Overrides the Graph API version used by the Facebook SDK.
  ///
  /// The plugin sets a default Graph API version at initialization because the
  /// Facebook SDK v18.x ships with an outdated default that has been removed by
  /// Meta. Call this as early as possible in app startup if you need a specific
  /// version before using plugin features that may trigger Graph API requests.
  ///
  /// The [version] string must be in the form `"vX.Y"` (e.g. `"v24.0"`).
  /// Refer to Meta's [Graph API changelog](https://developers.facebook.com/docs/graph-api/changelog/)
  /// for currently supported versions.
  ///
  /// See documentation:
  /// - [iOS Settings](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/settings.html)
  /// - [Android FacebookSdk](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/FacebookSdk.html)
  Future<void> setGraphApiVersion(String version) {
    return _channel.invokeMethod<void>('setGraphApiVersion', version);
  }

  /// Logs a product-catalog item so it can be matched for dynamic ads and
  /// product-catalog audiences.
  ///
  /// At least one of [gtin], [mpn] or [brand] must be provided — this is a
  /// requirement of the native SDK.
  ///
  /// See documentation:
  /// - [iOS](https://developers.facebook.com/docs/reference/iossdk/current/FBSDKCoreKit/classes/fbsdkappevents.html)
  /// - [Android](https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/appevents/appeventslogger.html)
  Future<void> logProductItem({
    required String itemId,
    required ProductAvailability availability,
    required ProductCondition condition,
    required String description,
    required String imageLink,
    required String link,
    required String title,
    required double priceAmount,
    required String currency,
    String? gtin,
    String? mpn,
    String? brand,
    Map<String, dynamic>? parameters,
  }) {
    assert(
      gtin != null || mpn != null || brand != null,
      'logProductItem requires at least one of gtin, mpn or brand.',
    );

    final args = <String, dynamic>{
      'itemId': itemId,
      'availability': availability.name,
      'condition': condition.name,
      'description': description,
      'imageLink': imageLink,
      'link': link,
      'title': title,
      'priceAmount': priceAmount,
      'currency': currency,
      'gtin': gtin,
      'mpn': mpn,
      'brand': brand,
      if (parameters != null) 'parameters': _normalizeParameters(parameters),
    };

    return _channel.invokeMethod<void>(
      'logProductItem',
      _filterOutNulls(args),
    );
  }

  /// Registers a push notification device [token] with the SDK so Meta can
  /// attribute push-driven app opens and measure push campaigns.
  ///
  /// Platform mapping:
  /// - iOS: `AppEvents.setPushNotificationsDeviceToken(_:)` (the String overload).
  ///   The underlying `setPushNotificationsDeviceTokenString:` Objective-C
  ///   selector is renamed to `setPushNotificationsDeviceToken(_:)` in Swift via
  ///   `NS_SWIFT_NAME`, so that is the symbol this plugin calls.
  /// - Android: `AppEventsLogger.setPushNotificationsRegistrationId`.
  Future<void> setPushNotificationsDeviceToken(String token) {
    return _channel.invokeMethod<void>(
      'setPushNotificationsDeviceToken',
      token,
    );
  }

  /// Registers a push notification [token] with the SDK.
  @Deprecated('Use setPushNotificationsDeviceToken instead, which follows the '
      'native SDK naming.')
  Future<void> setPushNotificationToken(String token) {
    return setPushNotificationsDeviceToken(token);
  }

  /// Sets the [FlushBehavior] controlling when events are sent to Meta.
  ///
  /// Use [FlushBehavior.explicitOnly] to suppress automatic flushing and only
  /// send events when [flush] is called.
  Future<void> setFlushBehavior(FlushBehavior behavior) {
    return _channel.invokeMethod<void>('setFlushBehavior', behavior.name);
  }

  /// Returns the current [FlushBehavior].
  Future<FlushBehavior> getFlushBehavior() async {
    final token = await _channel.invokeMethod<String>('getFlushBehavior');
    return flushBehaviorFromWire(token);
  }

  /// Returns the JSON-encoded hashed user data currently set on the SDK, or
  /// `null` if none has been set. See [setUserData].
  Future<String?> getUserData() {
    return _channel.invokeMethod<String>('getUserData');
  }

  /// Returns the user id previously set via [setUserID], or `null`.
  Future<String?> getUserID() {
    return _channel.invokeMethod<String>('getUserID');
  }

  /// Clears a single previously-set [field] of user data.
  ///
  /// Platform behavior:
  /// - iOS: clears the given field via `clearUserDataForType`.
  /// - Android: no-op. `AppEventsLogger` exposes no per-field clear; use
  ///   [clearUserData] to clear all fields at once.
  Future<void> clearUserDataForType(FacebookUserDataField field) {
    return _channel.invokeMethod<void>('clearUserDataForType', field.name);
  }

  /// Enables or disables verbose Facebook SDK debug logging (app events and
  /// network requests).
  ///
  /// This replaces the implicit debug-logging side effect that previously lived
  /// in the deprecated `setAdvertiserTracking` on Android; call this explicitly
  /// when you want SDK logs during development.
  Future<void> setDebugLoggingEnabled(bool enabled) {
    return _channel.invokeMethod<void>('setDebugLoggingEnabled', enabled);
  }

  // ---------------------------------------------------------------------------
  // ---------------------------------------------------------------------------
  //
  // PRIVATE METHODS BELOW HERE

  /// Creates a new map containing all of the key/value pairs from [parameters]
  /// except those whose value is `null`.
  Map<String, dynamic> _filterOutNulls(Map<String, dynamic> parameters) {
    final Map<String, dynamic> filtered = <String, dynamic>{};
    parameters.forEach((String key, dynamic value) {
      if (value != null) {
        filtered[key] = value;
      }
    });
    return filtered;
  }

  /// Normalizes event [parameters] to the value types accepted by the native
  /// SDKs: drops `null` entries, keeps `String`/`num` values, converts `bool`
  /// to `"1"`/`"0"`, and throws [ArgumentError] for anything else — the native
  /// SDKs silently drop the whole event when given an unsupported value type.
  Map<String, dynamic> _normalizeParameters(Map<String, dynamic> parameters) {
    final Map<String, dynamic> normalized = <String, dynamic>{};
    parameters.forEach((String key, dynamic value) {
      if (value == null) {
        return;
      } else if (value is bool) {
        normalized[key] = value ? paramValueYes : paramValueNo;
      } else if (value is String || value is num) {
        normalized[key] = value;
      } else {
        throw ArgumentError.value(
          value,
          key,
          'App event parameter values must be String, num, or bool. '
          'Encode structured values as a JSON string (json.encode) first.',
        );
      }
    });
    return normalized;
  }
}
